### ISSUE TITLE
Wrong abbreviation style in local.css

### ISSUE THREAD

**Issue by acabal** [davgross/henry-david-thoreau_a-yankee-in-canada#8]
If `lint` is complaining, the answer isn't to put an empty rule to shut it up... the answer is to find the correct rule that it is complaining about, which is in the typography manual: https://standardebooks.org/contribute/typography

Do a find on page for "abbr.name" for the correct rule to put in there

**Comment by davgross** [comment]
This would be good information to put in the lint error output. It's not always easy to find such information on the website.
